### ISSUE TITLE
koordinate mest

### ISSUE THREAD

**Issue by tinahawlina** [tinahawlina/APPR-2014-15#11]
Želela sem narediti koordinate mest, s tem, da bi jih le označila s krogci. Imam pa problem, ker mi meče vem napako 
Checking rgeos availability: FALSE
 	Note: when rgeos is not available, polygon geometry 	computations in maptools depend on gpclib,
 	which has a restricted licence. It is disabled by default;
 	to enable gpclib, type gpclibPermit()

Moram naložiti kak paket? Kaj je narobe?

**Comment by tinahawlina** [comment]
tole je pa koda:
```R 
drzavljanstvo <- table(moskiprosto$Nationality)
rekordi <- unique(drzavljanstvo)
rekordi <- rekordi[order(rekordi)]
barve <- rgb(1, 0, 0, match(drzavljanstvo, rekordi)/length(drzavljanstvo))
names(barve) <- names(drzavljanstvo)
plot(svet, col = barve[as.character(svet$name_long)])
title("Rekordi po državljanstvu")
legend("left", legend = rekordi, fill = rgb(1, 0, 0, (1:length(rekordi))/length(rekordi)), cex = 0.7)
imena <- c("Washington", "Canberra", "Paris","Brasilia")
mesta <- data.frame("long" = c(-77.03, 149.12, 2.35, -47.88), "lat"= c(38.90, -35.28, 48.85,  -15.79))
points(coordinates(mesta[c("long", "lat")]), col="black", cex=0.7)
dev.off() ```

**Comment by tinahawlina** [comment]
pa teh treh apostrofov nakoncu ni

**Comment by tinahawlina** [comment]
Zdej mi dela krogce, nevem kaj se je zgodilo :)

**Comment by jaanos** [comment]
Pri prvi objavi ne gre za napako - gre le za obvestilo, ki se pokaže vsakič, ko uvoziš knjižnico `maptools`.
