### ISSUE TITLE
sprememba starih imen držav, vzhodna/zahodna nemčija, sovjetska unija

### ISSUE THREAD

**Issue by tinahawlina** [tinahawlina/APPR-2014-15#13]
Takole sem poskusila spremeniti ime države, vendar programu ni všeč:
moskidelfin$Kraj.prvenstva[(gsub(".*, ", "", moskidelfin$Kraj.prvenstva) == "West Germany"] <- "Germany"
poskusila sem tudi brez gsub, da dam direktno vektor od vektorja, ampak ne gre. Je pa to v tabeli, pod stolpcem Kraj.prvenstva, pri čemer je pred tem napisano še mesto

**Comment by jaanos** [comment]
Po mojem bo najlažje tako:
```R
moskidelfin$Drzava.prvenstva <- gsub(".*, ", "", moskidelfin$Kraj.prvenstva)
moskidelfin$Drzava.prvenstva[grep("Germany", moskidelfin$Drzava.prvenstva)] <- "Germany"
```
Narediš torej nov stolpec, kjer so notri samo države. Potem hkrati poskrbiš za Vzhodno in Zahodno Nemčijo. Na isti način se potem lahko lotiš še ostalih držav.

Da ti bo pravilno izrisalo barve na zemljevid, se bo treba znebiti odvečnih presledkov v podatkih iz XML. Najlažje bo, če kar popraviš funkcijo `stripByPath` v `xml.r`:
```R
stripByPath <- function(x, path) {
  unlist(xpathApply(x, path,
                    function(y) gsub("[^A-Za-z0-9, ]", "",
                                gsub("^\\s*(.*?)\\s*$", "\\1",
                                gsub("^(.*?)\\[.*$", "\\1",
                                     xmlValue(y))))))
}
```

Še to: v `moskiprsno.R` in `zenskeprsno.R` se sklicuješ na stolpec `"Državljanstvo"` razpredelnic `moskiprsno` oziroma `zenskeprsno`, ki pa ju nimaš v podatkih, zato se ti program tam ustavi.

**Comment by tinahawlina** [comment]
Sem vse naredila, me pa zanima zakaj mi Rusije pri drugem grafu ne barva, čeprav sem jo spremenila?

**Comment by tinahawlina** [comment]
mi dela, morala sem zamenjat z russian federation.
