### ISSUE TITLE
problem z rusijo

### ISSUE THREAD

**Issue by tinahawlina** [tinahawlina/APPR-2014-15#14]
Pri prvem grafu imam v stolpcu Russia, česar se na zemljevidu ne zazna samo in jo moram spremeniti v Russian Federation. Zakaj to ne deluje?
moskiprosto$Nationality[moskiprosto$Nationality == "Russia"] <- "Russian Federation"

kako popravim?

**Comment by jaanos** [comment]
Problem je, ker je stolpec `Nationality` faktor, ki dovoli samo določene vrednosti. Morda bo najlažje, če ga pretvoriš v nize:
```R
moskiprosto$Nationality <- as.character(moskiprosto$Nationality)
```
Potem bo tvoj ukaz deloval pravilno.

**Comment by tinahawlina** [comment]
Hvala za odgovore :)
