### ISSUE TITLE
poročilo-vprašanje

### ISSUE THREAD

**Issue by tinahawlina** [tinahawlina/APPR-2014-15#15]
Je mogoče treba omejiti tudi višino grafov v poročilu?

**Comment by jaanos** [comment]
Vključene PDF-je seveda lahko omejiš tudi po višini - namesto `width` tako podaš parameter `height`, višino besedila pa dobiš s `\textheight`. Če želiš imeti grafe, ki so morda širši od besedila, si lahko pomagaš še z ukazom `\makebox`, da jih poravnaš na sredino strani, npr.:
```LaTeX
\makebox[\textwidth][c]{
\includegraphics[height=0.7\textheight]{../slike/moskidelfin_svet.pdf}
}
```
