### ISSUE TITLE
ženske hrbtno

### ISSUE THREAD

**Issue by tinahawlina** [tinahawlina/APPR-2014-15#16]
Nevem kaj je narobe, vendar še vedno izpisuje napako: 
Error in `$<-.data.frame`(`*tmp*`, "Čas", value = list()) : 
  replacement has 0 rows, data has 33
sem popravila črke tako kot ste napisali, vendar ne deluje. Pa še nekaj. Pri grafu moškidelfin sem popravila imena držav, vendar pri Nemčiji ne izpiše č-ja. Vse ostale šumnike iypisuje normalno.

**Comment by jaanos** [comment]
Vmes si pravilno popravila, a si pri združevanju pravo verzijo povozila z napačno verzijo. Napaka se zgodi, ker imaš v razpredelnici stolpec `Cas`, program pa pričakuje `Čas`. Da bi popravila, pojdi v RStudiu v okno, kjer delaš commit, in levo zgoraj klikni na _History_. Nato klikni na commit 5bf4b0a2 ter v spodnjem oknu desno nad spremembami datoteke `zenskehrbtno.csv` klikni na _View file @ 5bf4b0a2_. V oknu, ki se pojavi (ne glede na to, ali imaš namesto šumnikov vprašaje), klikni levo zgoraj na _Save As_ ter prepiši datoteko `zenskehrbtno.csv`. Potem bi moralo delovati. Pravo verzijo datoteke lahko sicer dobiš tudi z [GitHuba](https://raw.githubusercontent.com/tinahawlina/APPR-2014-15/5bf4b0a2c80bf943e02382f9a5d086497ae3158f/podatki/zenskehrbtno.csv).

Glede šumnikov v grafih sem ti napisal v pull requestu #17.
