### ISSUE TITLE
moskiprosto

### ISSUE THREAD

**Issue by tinahawlina** [tinahawlina/APPR-2014-15#18]
Ne riše mi normalno grafa in nevem kaj je narobe.

**Comment by jaanos** [comment]
Kaj natančno pa je narobe z grafom? Ko poženem tvoj program, se mi ta graf normalno izriše. Poskusi počistiti delovno okolje in še enkrat pognati celoten program (torej `projekt.r`).

Če imaš težave s šumniki, poskusi nadomestiti ukaz `pdf` s `cairo_pdf` - temu bo potrebno vsakič podati pisavo s parametrom `family` (npr. `family = "Arial"`). Če rišeš več kot en graf v datoteko PDF, bo potrebno dodati še parameter `onefile = TRUE`.

Morda se pa samo RStudio čudno obnaša - lahko ga poskušaš zapreti in nazaj odpreti.

**Comment by tinahawlina** [comment]
Error in plot.window(...) : need finite 'ylim' values
In addition: Warning messages:
1: In xy.coords(x, y, xlabel, ylabel, log) : NAs introduced by coercion
2: In min(x) : no non-missing arguments to min; returning Inf
3: In max(x) : no non-missing arguments to max; returning -Inf
4: In plot.window(...) : "cex.names" is not a graphical parameter
tole napiše.

**Comment by jaanos** [comment]
Imaš zadnjo verzijo naloženo na GitHubu? Sem poskusil še na Windowsih, pa tudi deluje.

Ti to javlja, ko rišeš v PDF, ali ko rišeš v RStudiu? V slednjem primeru je možno, da je velikost okenca za izris grafa v RStudiu premajhna, tako da jo lahko poskusiš povečati. Poglej še, kaj imaš v `moskiprosto[,3]` - glede na to, da rišeš stolpčni diagram, sicer ne bi smelo vplivati, tudi če bi tukaj bilo kaj narobe.

**Comment by tinahawlina** [comment]
Pdf-ja sploh odpreti noče, piše da je error. V RStudiu pa tudi ne nariše. 
In ja, imam zadnjo verzijo naloženo.

**Comment by jaanos** [comment]
Verjetno si večkrat pognala, pa se je vsakič ustavilo. Nekajkrat poženi `dev.off()` - dokler ne izpiše `null device`, potem pa poskusi še enkrat. Sicer pa bi moral ponoven zagon RStudia imeti enak učinek.

**Comment by tinahawlina** [comment]
Nič ne pomaga, sploh ne razumem.

**Comment by jaanos** [comment]
Če pa to spustiš (npr. če zakomentiraš `moskiprosto.R` v glavnem programu) pa deluje?

**Comment by tinahawlina** [comment]
Ja, tako pa dela.. hm.

**Comment by tinahawlina** [comment]
Zdaj pa spet ne deluje, pa sem samo odkomentirala, pognala in nazaj zakomentirala in spet pognala.

**Comment by tinahawlina** [comment]
Ma mogoče tole kaj smisla? Mogoče zato noče risat grafa?
Checking rgeos availability: FALSE
 	Note: when rgeos is not available, polygon geometry 	computations in maptools depend on gpclib,
 	which has a restricted licence. It is disabled by default;
 	to enable gpclib, type gpclibPermit()

**Comment by jaanos** [comment]
To obvestilo se izpiše ob uvozu knjižnic za risanje zemljevidov in ne vpliva na risanje grafov. Lahko ga sicer nekoliko reduciraš, če si namestiš še knjižnico `rgeos`.

A ti sedaj ne deluje, tudi če imaš spet zakomentirano - torej se problem pojavi še nekje drugje?

**Comment by tinahawlina** [comment]
Ne, ne deluje, čeprav je zakomentirano. Bom jaz jutri tole sporbala na faksu, mogoče je samo problem, da mojemu r-jeu kaj ni všeč.

**Comment by tinahawlina** [comment]
```R
Error in pdf("slike/moskiprosto.pdf") : invalid font type
In addition: Warning messages:
1: In pdf("slike/moskiprosto.pdf") :
  font family 'Arial' not found in PostScript font database
2: In pdf("slike/moskiprosto.pdf") :
  font family 'Arial' not found in PostScript font database
```
Na faksu tole izpiše, graf se pa nariše.

**Comment by jaanos** [comment]
Boš morala še enkrat izvesti korake iz datoteke `fontconfig.r`.

**Comment by tinahawlina** [comment]
Okej.

**Comment by tinahawlina** [comment]
Pri tem grafu moskiprosto, me zanima, če je vredu če angleška imena držav spremenim v slovenska kot vektorje
```R
moskiprosto$Nationality["Germany"] <- "Nemčija" 
```
takole?

**Comment by jaanos** [comment]
Tako ne bo šlo, saj stolpci razpredelnic nimajo imen. Lahko bi sicer indeksirala z ustreznim logičnim vektorjem, a bo morda bolje, če si pripraviš slovar in funkcijo za prevajanje - glej moj prvi odgovor pri LeaTehovnik/APPR-2014-15#11.

**Comment by tinahawlina** [comment]
Hvala :)

**Comment by tinahawlina** [comment]
Zdaj sem naredila slovar, vendar mam očitno napako, izpiše
```R
Error in axis(if (horiz) 2 else 1, at = at.l, labels = names.arg, lty = axis.lty,  : 
  formal argument "labels" matched by multiple actual arguments
In addition: Warning message:
In plot.window(xlim, ylim, log = log, ...) :
  "labels" is not a graphical parameter
```
Grafa pa tako ali tako ne vidim na svojem računalniku, tako da nevem. :S

**Comment by tinahawlina** [comment]
Pri vas deluje normalno?

**Comment by jaanos** [comment]
Glede na to, da rišeš stolpčne diagrame s `plot` (to bi lahko sicer počela tudi z `barplot`), ki hoče v tem primeru imeti faktorje, bo najlažje, če popraviš funkcijo `prevedi`:
```R
prevedi <- function(x) {
  factor(ifelse(is.na(slovar[x]), x, slovar[x]))
}
```
Ukaz `plot` ne pozna parametra `labels` - prevedena imena mu podaš s `prevedi(moskiprosto[,3])` kar kot prvi parameter (brez `names`, saj imaš imena držav kar v vektorju in ne v njegovih imenih).

**Comment by tinahawlina** [comment]
Sem popravila, grafa mi sicer še vedno ne izrisuje doma. Hvala!

**Comment by tinahawlina** [comment]
Graf zdaj izriše, hvala :)
