### ISSUE TITLE
analiza.r

### ISSUE THREAD

**Issue by tinahawlina** [tinahawlina/APPR-2014-15#19]
Narisala sem graf za ženske (delfin) v času, pa me zanima, kako lahko nekako združim vse te čase postavitev rekordov, da bi jih potem skupaj primerjala. Potem lažje naredim funkcijo glede na vse te podatke, pa tudi bolj smiselno se mi zdi tako. Bom dala na github zdajle.
Aja, pa tisti graf še kar ne dela.

**Comment by tinahawlina** [comment]
Poskusila sem ju takole dati notri, javi napako.
```R
Sys.setlocale("LC_TIME", "C") # naj uporablja angleška imena mesecev:
cas <- zenskedelfin$Čas
cas1 <- zenskehrbtno$Cas
datum <- names(table(zenskedelfin$Datum))
datum1 <- names(table(zenskehrbtno$Datum))
leto <- gsub(".*, ", "", datum)
leto1 <- gsub(".*, ", "", datum1)
names(leto) <- datum
names(leto1) <- datum1
plot(as.Date(zenskedelfin$Datum, "%b %d, %Y"), cas, as.Date(zenskehrbtno$Datum, "%b %d, %Y"), cas1, 
     main = "Postavitve rekordov v času", xlab = "Letnica postavitve rekorda", ylab = "Čas v sekundah", type = "h", lwd = 5, col = "salmon")
dev.off()
```

**Comment by jaanos** [comment]
Če želiš risati podatke iz več vektorjev risati na isti graf, bo treba ustrezne vektorje združiti:
```R
plot(c(as.Date(zenskedelfin$Datum, "%b %d, %Y"), as.Date(zenskehrbtno$Datum, "%b %d, %Y")), c(cas, cas1),
     main = "Postavitve rekordov v času", xlab = "Letnica postavitve rekorda", ylab = "Čas v sekundah", type = "h", lwd = 5, col = "salmon")
```
Lahko bi pa tudi naknadno dodajala elemente na obstoječ graf (lahko začneš s praznim) z ukazom `points` - potem bo morda lažje ločiti podatke glede na izvor (npr. z barvo).

Ti tisti graf tudi na faksu ni deloval?

**Comment by tinahawlina** [comment]
Danes potem nisem šla na faks, ker se nisem vredu počutila. Če pa naredim z grafom, potem različnim podatkom ne morem spreminjati barv?

**Comment by tinahawlina** [comment]
Sem spremenila barve.

**Comment by tinahawlina** [comment]
Hm, problem je, da so si grafi med seboj različni, mogoče bom

**Comment by tinahawlina** [comment]
Zdaj je tako, da graf skupaj nima veze s kakoršno koli funkcijo, ker so v nekaterih tehnikah bili rekordi postavljeni tudi dovolj pozno. Tako da je pomojem najboljše, da naredim primerjavo le v eni tehniki.

**Comment by jaanos** [comment]
Če rišeš vse podatke hkrati s `plot`, bi morala za ustrezno barvanje podati vektor z ustrezno barvo za vsako točko. Če imaš samo nekaj kategorij za barve (ali oblike itd.), je potem morda lažje, če za vsako barvo posebej ustrezne podatke rišeš hkrati z ukazom `points`, ki mu lahko potem podaš samo eno barvo namesto celotnega vektorja.

V zgornjem primeru so podatki izgledali neprimerljivi, tako da se strinjam, da bo bolje delati napovedi za vsako tehniko posebej.
